<table width="650" border="0" cellspacing="0" cellpadding="0" align="center">
   <tr>
    <td align="center" class="font8" valign="bottom"><b>电话: (022)24966266&nbsp;&nbsp;&nbsp;    FAX: (022)24395492&nbsp;&nbsp;&nbsp;    E-MAIL : key-one@ycpiano.co.kr</b></td>
  </tr>
   <tr>
    <td height="3" bgcolor="#002F53"></td>
  </tr>
  <tr>
    <td align="center"><img src="/ui/images/ko/report/fax_footer.gif" /></td>
  </tr>
</table>