<table width="650" cellspacing="0" cellpadding="0" style="border-collapse:collapse;" border="1" bordercolor="#002F53" align="center">
  <tr>
    <td height="18" bgcolor="#002F53"></td>
  </tr>
  <tr>
    <td align="center" valign="middle" height="85"><img src="/ui/images/ko/report/fax_logo.gif" width="541" height="66" /></td>
  </tr>
  <tr>
    <td height="5" bgcolor="#002F53"></td>
  </tr>
</table>


<table width="650" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td align="center" class="font8"><b>电话: (022)24966266&nbsp;&nbsp;&nbsp;    FAX: (022)24395492&nbsp;&nbsp;&nbsp;    E-MAIL : key-one@ycpiano.co.kr</b></td>
  </tr>
</table>