<%
String Top_HTML = "";
String Bottom_HTML = "";

Top_HTML += "";

/*
Top_HTML += "<div align='center'> ";
Top_HTML += "<table width='100%' border='0' cellspacing='0' cellpadding='0'>";
Top_HTML += "	<tr>";
Top_HTML += "		<td class='font3'>HYUNDAI MOTOR INDIA LIMITED</td>";
Top_HTML += "	</tr>";
Top_HTML += "	<tr>";
Top_HTML += "		<td><span class='style5'>Rdgd. Office &amp; Factory : Plot No, H-1, SIPCOT Industrial Park, Irrungattukottai, </span></td>";
Top_HTML += "	</tr>";
Top_HTML += "	<tr>";
Top_HTML += "		<td><span class='style5'>Sriperu ...Udur Taluk, Kancheepuram Dist. Tamilnadu-602 105 </span></td>";
Top_HTML += "	</tr>";
Top_HTML += "	<tr>";
Top_HTML += "		<td><span class='style5'>Tel : 044-47100000 Fax: 044-47100600 </span></td>";
Top_HTML += "	</tr>";
Top_HTML += "	<tr>";
Top_HTML += "		<td><img src='{{ER_EagletReportUrl}}/report_img/text1.gif' /></td>";
Top_HTML += "	</tr>";
Top_HTML += "</table>";
Top_HTML += "</div>";
*/

%>




